### ISSUE TITLE
May I ask you for a dataset of this paper?

### ISSUE THREAD

**Issue by Kdetian** [cfl-minds/gnn_laminar_flow#4]
We are deeply inspired by your paper, so we want to continue to do some work related to your paper and quote your paper. But the link you given before is invalid.

**Comment by jviquerat** [comment]
Which link did you use ?

**Comment by Kdetian** [comment]
this one:



https://cloud.mines-paristech.fr/index.php/s/8MAdWJOCRqaazE3
thanks

                       
Original Email
                       
                     

Sender:"Jonathan Viquerat"< ***@***.*** &gt;;

Sent Time:2023/2/17 21:44

To:"cfl-minds/gnn_laminar_flow"< ***@***.*** &gt;;

Cc recipient:"Kdetian"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [cfl-minds/gnn_laminar_flow] May I ask you for a dataset of thispaper? (Issue #4)




 
Which link did you use ?

**Comment by jviquerat** [comment]
Please contact me via email : jonathan.viquerat@mines-paristech.fr
