### ISSUE TITLE
Some questions?

### ISSUE THREAD

**Issue by miyuan-beipiao** [cfl-minds/gnn_laminar_flow#6]
In the [gnn_laminar_flow](https://github.com/cfl-minds/gnn_laminar_flow)/network_utils.py / Line 25:
**_updates = tf.math.add(tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes), tf.math.unsorted_segment_sum(
        messages, edges[:, 1], n_nodes))  # aggregate the edge messages around every node_**
For example, the i-th node should aggregate the edge around it, however, the code above maybe mean that the i-th code not only  aggregates the edge around it, but also some other related or not related edge, which is not shown in the paper equation (4)

**Comment by jviquerat** [comment]
@gmhaber @junfeng-chen maybe you can give a look at this ?

**Comment by junfeng-chen** [comment]
> ... but also some other related or not related edge, which is not shown in the paper equation (4)

@miyuan-beipiao Can you make it clear which unrelated edges are possibly aggregated ?
